name: Browser Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest  # Windows also supported with 'windows-latest'

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install
          playwright install-deps  # Required for Linux

      # Run tests
      - name: Run automated tests
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          HEADLESS: "True"
          BROWSER_TYPE: "chromium"  # chromium, firefox, or webkit
        run: python -m core.run_all

      # Upload test artifacts
      - name: Upload test results
        if: always()  # Run even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ github.run_number }}
          path: |
            reports/
            screenshots/
            test_report.json