name: Browser Automation Tests

on: [push, pull_request]  # Triggers on every push/PR

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Checks out your code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install
          playwright install-deps  # Linux browser dependencies

      - name: Run tests
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          HEADLESS: "true"
        run: python -m core.run_all  # Your test runner

      - name: Upload results
        if: always()  # Upload even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            reports/
            screenshots/
            test_report.json