name: Browser Automation Tests

on: [push, pull_request]

env:
  PYTHON_VERSION: '3.11'
  PLAYWRIGHT_VERSION: '1.42.0'
  BROWSER_TYPE: 'chromium'
  PLAYWRIGHT_HEADLESS: '1'

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgbm-dev \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libdrm-dev \
            libxkbcommon-dev \
            libgtk-3-dev \
            libasound2 \
            xvfb

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright==${{ env.PLAYWRIGHT_VERSION }}
          python -m playwright install --with-deps ${{ env.BROWSER_TYPE }}

      - name: Load .env file
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "HEADLESS=true" >> .env
          echo "BROWSER_TYPE=chromium" >> .env

      - name: Run tests with xvfb
        env:
          DISPLAY: ':99'  # Set display for xvfb
          PLAYWRIGHT_HEADLESS: "1"
          BROWSER_TYPE: "chromium"
          TEST_TIMEOUT: "120"
        run: |
          mkdir -p reports screenshots
          # Start xvfb in background
          Xvfb :99 -screen 0 1280x1024x16 &
          # Run tests
          python -m run_all
          
          if [ ! -f "test_report.json" ]; then
            echo "❌ Error: No JSON report generated"
            exit 1
          fi
          
          if [ -z "$(ls reports/*.html)" ]; then
            echo "❌ Error: No HTML report generated"
            exit 1
          fi

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_number }}
          path: |
            reports/
            screenshots/
            test_report.json
