name: Browser Automation Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'pydantic>=2.10.4,<2.11.0'
          pip install langchain-google-genai
          pip install -r requirements.txt
          playwright install
          playwright install-deps

      - name: Run tests and generate reports
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          HEADLESS: "true"
        run: |
          # Clean and setup
          rm -rf reports/*
          mkdir -p reports screenshots
          
          # Run tests - this should create both reports
          python -m run_all
          
          # Simple verification
          echo "Checking reports:"
          ls -la reports/ || echo "No reports directory"
          [ -f "test_report.json" ] && echo "JSON report exists" || echo "No JSON report"
          [ -f "reports/report.html" ] && echo "HTML report exists" || echo "No HTML report"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            reports/
            screenshots/
            test_report.json
          retention-days: 3