name: Browser Automation Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/browser-use/browser-use.git
          pip install -r requirements.txt
          playwright install
          playwright install-deps

      - name: Run tests
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          HEADLESS: "true"
        run: python -m core.run_all

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: test-results
          path: |
            reports/
            screenshots/
            test_report.json